debug: true
server_addr: "192.168.1.211:4443"
redis:
  addrs:
    server1: "172.16.10.211:6379"
  db: 0
  pool_size: 8
postgre:
  enable: true
  host: "172.16.10.211"
  port: "5432"
  pool_max_conns: 5
cache:
  expiration: "10m"
  cleanup: "15m"
log:
  format: "postgre"
  table: "log"