debug: true
server_addr: "192.168.1.8:4443"
redis:
  enable: true
  addrs:
    server1: "127.0.0.1:6379"
  db: 0
  pool_size: 8
postgre:
  enable: false
  host: "127.0.0.1"
  port: "5432"
  pool_max_conns: 5
cache:
  expiration: "10m"
  cleanup: "15m"
log:
  format: "file"
  table: "log"